"""add new column placeholder and update value datatype to string

Revision ID: 01aad5da62e5
Revises: d132a9bf1803
Create Date: 2026-05-25 01:54:32.450866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '01aad5da62e5'
down_revision: Union[str, Sequence[str], None] = 'd132a9bf1803'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    result = bind.execute(sa.text(
        "SELECT COUNT(*) FROM information_schema.TABLE_CONSTRAINTS "
        "WHERE TABLE_NAME='rules' AND CONSTRAINT_NAME='uq_rule_combination' AND CONSTRAINT_TYPE='UNIQUE'"
    ))
    if result.scalar():
        op.drop_constraint('uq_rule_combination', 'rules', type_='unique')
    op.alter_column('rules', 'value',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
    col_exists = bind.execute(sa.text(
        "SELECT COUNT(*) FROM information_schema.COLUMNS "
        "WHERE TABLE_NAME='rules' AND COLUMN_NAME='placeholder'"
    )).scalar()
    if not col_exists:
        op.add_column('rules', sa.Column('placeholder', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('uq_rule_combination'), 'rules', ['field_name', 'operator', 'value'], unique=True)
    op.alter_column('rules', 'value',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('rules', 'placeholder')
    # ### end Alembic commands ###
