"""remove placeholder no use

Revision ID: 693a3b73132c
Revises: 80842913488d
Create Date: 2026-05-25 20:18:12.500940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '693a3b73132c'
down_revision: Union[str, Sequence[str], None] = '80842913488d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rules', 'placeholder')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rules', sa.Column('placeholder', mysql.TEXT(), nullable=True))
    # ### end Alembic commands ###
