"""add unique constraint to rules

Revision ID: 77adacd45c44
Revises: 9dda891da0e6
Create Date: 2026-05-24 13:42:05.024769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77adacd45c44'
down_revision: Union[str, Sequence[str], None] = '9dda891da0e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_rule_combination', 'rules', ['field_name', 'operator', 'value'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_rule_combination', 'rules', type_='unique')
    # ### end Alembic commands ###
