"""remove name from rules fix operator length

Revision ID: 9dda891da0e6
Revises: 62873de640bb
Create Date: 2026-05-24 11:18:27.033069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9dda891da0e6'
down_revision: Union[str, Sequence[str], None] = '62873de640bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rules', 'operator',
               existing_type=mysql.VARCHAR(length=2),
               type_=sa.String(length=3),
               existing_nullable=False)
    op.drop_column('rules', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rules', sa.Column('name', mysql.VARCHAR(length=255), nullable=False))
    op.alter_column('rules', 'operator',
               existing_type=sa.String(length=3),
               type_=mysql.VARCHAR(length=2),
               existing_nullable=False)
    # ### end Alembic commands ###
