"""add indexes in contract

Revision ID: d132a9bf1803
Revises: 77adacd45c44
Create Date: 2026-05-24 13:48:35.682778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd132a9bf1803'
down_revision: Union[str, Sequence[str], None] = '77adacd45c44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('index_company_active_contract', 'contracts', ['company_id', 'is_active'], unique=False)
    op.create_index('index_company_contract_id', 'contracts', ['company_id'], unique=False)
    op.create_index('index_user_contract_id', 'contracts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('index_user_contract_id', table_name='contracts')
    op.drop_index('index_company_contract_id', table_name='contracts')
    op.drop_index('index_company_active_contract', table_name='contracts')
    # ### end Alembic commands ###
